//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import <UIKit/UIKit.h>
#import "BCWebViewController.h"
#import "AccountsAndAddressesNavigationController.h"
#import "SendBitcoinViewController.h"
#import "TransactionsViewController.h"
#import "TransactionsBitcoinViewController.h"
#import "TransactionsBitcoinCashViewController.h"
#import "AssetSelectorView.h"
#import "Assets.h"
#import "BCConfirmPaymentViewModel.h"
#import "BCModalView.h"
#import "BCNavigationController.h"
#import "BCNavigationController.h"
#import "BuyBitcoinNavigationController.h"
#import "BuyBitcoinViewController.h"
#import "DebugTableViewController.h"
#import "ECSlidingViewController.h"
#import "GraphTimeFrame.h"
#import "KeychainItemWrapper+Credentials.h"
#import "KeychainItemWrapper+SwipeAddresses.h"
#import "KeychainItemWrapper.h"
#import "ModuleXMLHttpRequest.h"
#import "MultiAddressResponse.h"
#import "NSData+Hex.h"
#import "NSNumberFormatter+Currencies.h"
#import "NSString+SHA256.h"
#import "Reachability.h"
#import "SettingsNavigationController.h"
#import "TabControllerManager.h"
#import "Transaction.h"
#import "TransferAllFundsViewController.h"
#import "UIApplication+Suspend.h"
#import "UIDevice+Hardware.h"
#import "UIViewController+AutoDismiss.h"
#import "Wallet.h"
#import "TransactionEtherTableViewCell.h"
#import "WebLoginViewController.h"
#import "BCInsetLabel.h"
#import "TransactionTableCell.h"
#import "TransactionDetailViewModel.h"
#import "TransactionDetailNavigationController.h"
#import "TransactionDetailViewController.h"
#import "NSDateFormatter+VerboseString.h"
// Settings
#import "SettingsWebViewController.h"
#import "KeychainItemWrapper+SwipeAddresses.h"
#import "BCVerifyEmailViewController.h"
#import "BCVerifyMobileNumberViewController.h"
#import "SettingsSelectorTableViewController.h"
#import "SettingsChangePasswordViewController.h"

#import "FromToView.h"
#import "ContinueButtonInputAccessoryView.h"

#import "ExchangeTrade.h"
#import "NSDateFormatter+TimeAgoString.h"
#import "UIView+ChangeFrameAttribute.h"

#import "UILabel+CGRectForSubstring.h"
#import "UILabel+Animations.h"
