//
//  LocalizationConstants.h
//  Blockchain
//
//  Created by Tim Lee on 8/6/14.
//  Copyright (c) 2014 Blockchain Luxembourg S.A. All rights reserved.
//
#import <Foundation/Foundation.h>

#define BC_STRING_ALL_WALLETS NSLocalizedString(@"All Wallets", nil)
#define BC_STRING_WALLETS NSLocalizedString(@"Wallets", nil)

#define BC_STRING_ANY_ADDRESS NSLocalizedString(@"Any address", nil)
#define BC_STRING_ARGUMENT_ADDRESSES NSLocalizedString(@"%d addresses", nil)
#define BC_STRING_ARGUMENT_ADDRESS NSLocalizedString(@"%d address", nil)
#define BC_STRING_NO_ADDRESSES_WITH_SPENDABLE_BALANCE_ABOVE_OR_EQUAL_TO_DUST NSLocalizedString(@"You have no addresses with a spendable balance greater than or equal to the required dust threshold.", nil)
#define BC_STRING_SOME_FUNDS_CANNOT_BE_TRANSFERRED_AUTOMATICALLY NSLocalizedString(@"Some funds cannot be transferred automatically.", nil)

#define BC_STRING_ENTER_BITCOIN_ADDRESS_OR_SELECT NSLocalizedString(@"Enter Bitcoin address or select", nil)
#define BC_STRING_ENTER_ETHER_ADDRESS NSLocalizedString(@"Enter Ether address", nil)
#define BC_STRING_YOU_MUST_ENTER_DESTINATION_ADDRESS NSLocalizedString(@"You must enter a destination address", nil)
#define BC_STRING_INVALID_TO_BITCOIN_ADDRESS NSLocalizedString(@"Invalid to bitcoin address", nil)
#define BC_STRING_FROM_TO_DIFFERENT NSLocalizedString(@"From and destination have to be different", nil)
#define BC_STRING_FROM_TO_ADDRESS_DIFFERENT NSLocalizedString(@"From and destination address have to be different", nil)
#define BC_STRING_INVALID_SEND_VALUE NSLocalizedString(@"Invalid Send Value", nil)

#define BC_STRING_SIGNING_INPUTS NSLocalizedString(@"Signing Inputs", nil)
#define BC_STRING_SIGNING_INPUT NSLocalizedString(@"Signing Input %d", nil)
#define BC_STRING_FINISHED_SIGNING_INPUTS NSLocalizedString(@"Finished Signing Inputs", nil)
#define BC_STRING_TRANSFER_ALL_FROM_ADDRESS_ARGUMENT_ARGUMENT NSLocalizedString(@"Transferring all funds: Address %i of %i", nil)
#define BC_STRING_TRANSFER_ALL_CALCULATING_AMOUNTS_AND_FEES_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Calculating: Address %@ of %@", nil)
#define BC_STRING_TRANSFER_ALL_PREPARING_TRANSFER NSLocalizedString(@"Preparing transfer", nil)

#define BC_STRING_ADD_TO_ADDRESS_BOOK NSLocalizedString(@"Add to Address book?", nil)
#define BC_STRING_NO NSLocalizedString(@"No", nil)
#define BC_STRING_YES NSLocalizedString(@"Yes", nil)
#define BC_STRING_SEND NSLocalizedString(@"Send", nil)
#define BC_STRING_NO_AVAILABLE_FUNDS NSLocalizedString(@"You have no available funds to send from this address", nil)
#define BC_STRING_MUST_BE_ABOVE_OR_EQUAL_TO_DUST_THRESHOLD NSLocalizedString(@"Amount must be greater than or equal to the dust threshold (%lld Satoshi)", nil)
#define BC_STRING_RECEIVE NSLocalizedString(@"Receive", nil)
#define BC_STRING_TRANSACTIONS NSLocalizedString(@"Transactions", nil)
#define BC_STRING_LOAD_MORE_TRANSACTIONS NSLocalizedString(@"Load More Transactions", nil)
#define BC_STRING_SENDING_TRANSACTION NSLocalizedString(@"Sending Transaction", nil)
#define BC_STRING_USE_TOTAL_AVAILABLE_MINUS_FEE_ARGUMENT NSLocalizedString(@"Use total available minus fee: %@", nil)

#define BC_STRING_PAYMENT_SENT NSLocalizedString(@"Payment Sent!", nil)
#define BC_STRING_PAYMENT_SENT_ETHER NSLocalizedString(@"Payment Sent! Your balance and transactions will update soon.", nil)
#define BC_STRING_WAITING_FOR_ETHER_PAYMENT_TO_FINISH_TITLE NSLocalizedString(@"Waiting for payment", nil)
#define BC_STRING_WAITING_FOR_ETHER_PAYMENT_TO_FINISH_MESSAGE NSLocalizedString(@"Please wait until your last ether transaction confirms.", nil)
#define BC_STRING_PAYMENTS_SENT NSLocalizedString(@"Payments Sent", nil)
#define BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT NSLocalizedString(@"Transferred funds from %d %@", nil)
#define BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT_OUTPUTS_ARGUMENT_ARGUMENT_TOO_SMALL NSLocalizedString(@"Transferred funds from %d %@. Outputs for %d %@ were too small.", nil)
#define BC_STRING_PAYMENT_ASK_TO_ARCHIVE_TRANSFERRED_ADDRESSES NSLocalizedString(@"Would you like to archive the addresses used?", nil)
#define BC_STRING_PAYMENT_RECEIVED NSLocalizedString(@"Payment Received", nil)
#define BC_STRING_RECEIVE_SCREEN_INSTRUCTIONS NSLocalizedString(@"Tap to copy this address. Share it with the sender via email or text.", nil)
#define BC_STRING_ERROR_COPYING_TO_CLIPBOARD NSLocalizedString(@"An error occurred while copying your address to the clipboard. Please re-select the destination address or restart the app and try again.", nil)

#define BC_STRING_TRADE_COMPLETED NSLocalizedString(@"Trade Completed", nil)
#define BC_STRING_THE_TRADE_YOU_CREATED_ON_DATE_ARGUMENT_HAS_BEEN_COMPLETED NSLocalizedString(@"The trade you created on %@ has been completed!", nil)
#define BC_STRING_VIEW_DETAILS NSLocalizedString(@"View details", nil)
#define BC_STRING_BUY_WEBVIEW_ERROR_MESSAGE NSLocalizedString(@"Something went wrong, please try reopening Buy & Sell Bitcoin again.", nil)

#define BC_STRING_CONFIRM_PAYMENT NSLocalizedString(@"Confirm Payment", nil)
#define BC_STRING_ADJUST_FEE NSLocalizedString(@"Adjust Fee", nil)
#define BC_STRING_ASK_TO_ADD_TO_ADDRESS_BOOK NSLocalizedString(@"Would you like to add the bitcoin address %@ to your address book?", nil)
#define BC_STRING_ARGUMENT_COPIED_TO_CLIPBOARD NSLocalizedString(@"%@ copied to clipboard", nil)
#define BC_STRING_COPIED_TO_CLIPBOARD NSLocalizedString(@"Copied to clipboard", nil)
#define BC_STRING_SEND_FROM NSLocalizedString(@"Send from...", nil)
#define BC_STRING_SEND_TO NSLocalizedString(@"Send to...", nil)
#define BC_STRING_RECEIVE_TO NSLocalizedString(@"Receive to...", nil)
#define BC_STRING_WHERE NSLocalizedString(@"Where", nil)

#define BC_STRING_SEND_TO_ADDRESS NSLocalizedString(@"Send to address", nil)

#define BC_STRING_YOU_MUST_ENTER_A_LABEL NSLocalizedString(@"You must enter a label", nil)
#define BC_STRING_LABEL_MUST_HAVE_LESS_THAN_18_CHAR NSLocalizedString(@"Label must have less than 18 characters", nil)
#define BC_STRING_LABEL_MUST_BE_ALPHANUMERIC NSLocalizedString(@"Label must contain letters and numbers only", nil)
#define BC_STRING_UNARCHIVE NSLocalizedString(@"Unarchive", nil)
#define BC_STRING_ARCHIVE NSLocalizedString(@"Archive", nil)
#define BC_STRING_ARCHIVING_ADDRESSES NSLocalizedString(@"Archiving addresses", nil)
#define BC_STRING_ARCHIVED NSLocalizedString(@"Archived", nil)
#define BC_STRING_NO_LABEL NSLocalizedString(@"No Label", nil)
#define BC_STRING_TRANSACTIONS_COUNT NSLocalizedString(@"%d Transactions", nil)
#define BC_STRING_LOADING_EXTERNAL_PAGE NSLocalizedString(@"Loading External Page", nil)

#define BC_STRING_PASSWORD_NOT_STRONG_ENOUGH NSLocalizedString(@"Your password is not strong enough. Please choose a different password.", nil)
#define BC_STRING_PASSWORD_MUST_BE_LESS_THAN_OR_EQUAL_TO_255_CHARACTERS NSLocalizedString(@"Password must be less than or equal to 255 characters", nil)
#define BC_STRING_PASSWORDS_DO_NOT_MATCH NSLocalizedString(@"Passwords do not match", nil)
#define BC_STRING_PASSWORD_MUST_BE_DIFFERENT_FROM_YOUR_EMAIL NSLocalizedString(@"Password must be different from your email", nil)
#define BC_STRING_NEW_PASSWORD_MUST_BE_DIFFERENT NSLocalizedString(@"New password must be different", nil)
#define BC_STRING_PLEASE_PROVIDE_AN_EMAIL_ADDRESS NSLocalizedString(@"Please provide an email address.", nil)
#define BC_STRING_PLEASE_VERIFY_EMAIL_ADDRESS_FIRST NSLocalizedString(@"Please verify your email address first.", nil)
#define BC_STRING_PLEASE_VERIFY_MOBILE_NUMBER_FIRST NSLocalizedString(@"Please verify your mobile number first.", nil)
#define BC_STRING_INVALID_EMAIL_ADDRESS NSLocalizedString(@"Invalid email address.", nil)
#define BC_STRING_MY_BITCOIN_WALLET NSLocalizedString(@"My Bitcoin Wallet", nil)
#define BC_STRING_PASSWORD_STRENGTH_WEAK NSLocalizedString(@"Weak", nil)
#define BC_STRING_PASSWORD_STRENGTH_REGULAR NSLocalizedString(@"Regular", nil)
#define BC_STRING_PASSWORD_STRENGTH_NORMAL NSLocalizedString(@"Normal", nil)
#define BC_STRING_PASSWORD_STRENGTH_STRONG NSLocalizedString(@"Strong", nil)

#define BC_STRING_UNCONFIRMED NSLocalizedString(@"Unconfirmed", nil)
#define BC_STRING_COUNT_CONFIRMATIONS NSLocalizedString(@"%d Confirmations", nil)
#define BC_STRING_ARGUMENT_CONFIRMATIONS NSLocalizedString(@"%@ Confirmations", nil)

#define BC_STRING_TRANSFERRED NSLocalizedString(@"Transferred", nil)
#define BC_STRING_RECEIVED NSLocalizedString(@"Received", nil)
#define BC_STRING_SENT NSLocalizedString(@"Sent", nil)

#define BC_STRING_ERROR NSLocalizedString(@"Error", nil)

#define BC_STRING_LEARN_MORE NSLocalizedString(@"Learn More", nil)
#define BC_STRING_IMPORT_PRIVATE_KEY NSLocalizedString(@"Import Private Key", nil)
#define BC_STRING_DECRYPTING_PRIVATE_KEY NSLocalizedString(@"Decrypting Private Key", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY NSLocalizedString(@"Extended Public Key", nil)

#define BC_STRING_SCAN_PAIRING_CODE NSLocalizedString(@"Scan Pairing Code", nil)
#define BC_STRING_PARSING_PAIRING_CODE NSLocalizedString(@"Parsing Pairing Code", nil)
#define BC_STRING_INVALID_PAIRING_CODE NSLocalizedString(@"Invalid Pairing Code", nil)

#define BC_STRING_INSUFFICIENT_FUNDS NSLocalizedString(@"Insufficient Funds", nil)
#define BC_STRING_PLEASE_SELECT_DIFFERENT_ADDRESS NSLocalizedString(@"Please select a different address to send from.", nil)

#define BC_STRING_OK NSLocalizedString(@"OK", nil)
#define BC_STRING_OPEN_MAIL_APP NSLocalizedString(@"Open Mail App", nil)
#define BC_STRING_CANNOT_OPEN_MAIL_APP NSLocalizedString(@"Cannot open Mail App", nil)

//#define BC_STRING_REQUEST_FAILED_PLEASE_CHECK_INTERNET_CONNECTION NSLocalizedString(@"Request failed. Please check your internet connection.", nil)
#define BC_STRING_SOMETHING_WENT_WRONG_CHECK_INTERNET_CONNECTION NSLocalizedString(@"An error occurred while updating your spendable balance. Please check your internet connection and try again.", nil)
#define BC_STRING_EMPTY_RESPONSE NSLocalizedString(@"Empty response from server.", nil)

#define BC_STRING_FORGET_WALLET NSLocalizedString(@"Forget Wallet", nil)

#define BC_STRING_CLOSE_APP NSLocalizedString(@"Close App", nil)

#define BC_STRING_INVALID_GUID NSLocalizedString(@"Invalid Wallet ID", nil)

#define BC_STRING_ENTER_YOUR_CHARACTER_WALLET_IDENTIFIER NSLocalizedString(@"Please enter your 36 character wallet identifier correctly. It can be found in the welcome email on startup.", nil)
#define BC_STRING_INVALID_IDENTIFIER NSLocalizedString(@"Invalid Identifier", nil)

#define BC_STRING_DISABLE_TWO_FACTOR NSLocalizedString(@"You must have two-factor authentication disabled to pair manually.", nil)
#define BC_STRING_WATCH_ONLY NSLocalizedString(@"Watch Only", nil)
#define BC_STRING_WATCH_ONLY_RECEIVE_WARNING NSLocalizedString(@"You are about to receive bitcoin to a watch-only address. You can only spend these funds if you have access to the private key. Continue?", nil)
#define BC_STRING_USER_DECLINED NSLocalizedString(@"User Declined", nil)
#define BC_STRING_CHANGE_PIN NSLocalizedString(@"Change PIN", nil)
#define BC_STRING_ADDRESS NSLocalizedString(@"Address", nil)
#define BC_STRING_BITCOIN_ADDRESSES NSLocalizedString(@"Bitcoin Addresses", nil)
#define BC_STRING_ADDRESSES NSLocalizedString(@"Addresses", nil)
#define BC_STRING_SETTINGS NSLocalizedString(@"Settings", nil)
#define BC_STRING_BACKUP NSLocalizedString(@"Backup", nil)
#define BC_STRING_BACKUP_FUNDS NSLocalizedString(@"Backup Funds", nil)
#define BC_STRING_START_BACKUP NSLocalizedString(@"START BACKUP", nil)
#define BC_STRING_BACKUP_NEEDED NSLocalizedString(@"Backup Needed", nil)
#define BC_STRING_ADD_EMAIL NSLocalizedString(@"Add Email", nil)
#define BC_STRING_BUY_AND_SELL_BITCOIN NSLocalizedString(@"Buy & Sell Bitcoin", nil)

#define BC_STRING_WARNING NSLocalizedString(@"Warning!!!", nil)
#define BC_STRING_NEXT NSLocalizedString(@"Next", nil)
#define BC_STRING_CANCEL NSLocalizedString(@"Cancel", nil)
#define BC_STRING_DISMISS NSLocalizedString(@"Dismiss", nil)
#define BC_STRING_DELETE NSLocalizedString(@"Delete", nil)
#define BC_STRING_CONFIRM NSLocalizedString(@"Confirm", nil)
#define BC_STRING_CANCELLING NSLocalizedString(@"Cancelling", nil)
#define BC_STRING_HOW_WOULD_YOU_LIKE_TO_PAIR NSLocalizedString(@"How would you like to pair?", nil)
#define BC_STRING_MANUALLY NSLocalizedString(@"Manually", nil)
#define BC_STRING_AUTOMATICALLY NSLocalizedString(@"Automatically", nil)
#define BC_STRING_ENTER_PIN NSLocalizedString(@"Enter PIN", nil)
#define BC_STRING_PLEASE_ENTER_PIN NSLocalizedString(@"Please enter your PIN", nil)
#define BC_STRING_PLEASE_ENTER_NEW_PIN NSLocalizedString(@"Please enter a new PIN", nil)
#define BC_STRING_CONFIRM_PIN NSLocalizedString(@"Confirm your PIN", nil)
#define BC_STRING_WARNING_TITLE NSLocalizedString(@"Warning", nil)

#define BC_STRING_PAYMENT_REQUEST_BITCOIN_ARGUMENT_ARGUMENT NSLocalizedString(@"Please send %@ to bitcoin address.\n%@", nil)
#define BC_STRING_PAYMENT_REQUEST_BITCOIN_CASH_ARGUMENT NSLocalizedString(@"Please send BCH to the Bitcoin Cash address\n%@", nil)
#define BC_STRING_PAYMENT_REQUEST_ETHER_ARGUMENT NSLocalizedString(@"Please send ether to %@.", nil)
#define BC_STRING_AMOUNT NSLocalizedString(@"Amount", nil)
#define BC_STRING_PAYMENT_REQUEST_HTML NSLocalizedString(@"Please send payment to bitcoin address (<a href=\"https://blockchain.info/wallet/bitcoin-faq\">help?</a>): %@", nil)
#define BC_STRING_PAYMENT_REQUEST_ETHER_SUBJECT NSLocalizedString(@"Ether payment request", nil)
#define BC_STRING_CLOSE NSLocalizedString(@"Close", nil)

#define BC_STRING_TRANSACTION_DETAILS NSLocalizedString(@"Transaction details", nil)

#define BC_STRING_CREATE NSLocalizedString(@"Create", nil)
#define BC_STRING_NAME NSLocalizedString(@"Name", nil)
#define BC_STRING_EDIT NSLocalizedString(@"Edit", nil)
#define BC_STRING_LABEL NSLocalizedString(@"Label", nil)

#define BC_STRING_DONE NSLocalizedString(@"Done", nil)
#define BC_STRING_SAVE NSLocalizedString(@"Save", nil)
#define BC_STRING_CREATE_WALLET NSLocalizedString(@"Create Wallet", nil)

#define BC_STRING_ACCOUNTS NSLocalizedString(@"Accounts", nil)
#define BC_STRING_TOTAL_BALANCE NSLocalizedString(@"Total Balance", nil)
#define BC_STRING_IMPORTED_ADDRESSES NSLocalizedString(@"Imported Addresses", nil)
#define BC_STRING_IMPORTED_ADDRESSES_ARCHIVED NSLocalizedString(@"Imported Addresses (Archived)", nil)

#define BC_STRING_UPGRADE_TO_V3 NSLocalizedString(@"Upgrade to V3", nil)

#define BC_STRING_ADDRESS_BOOK NSLocalizedString(@"Address book", nil)

#define BC_STRING_LOADING_VERIFYING NSLocalizedString (@"Verifying", nil)
#define BC_STRING_LOADING_DECRYPTING_WALLET NSLocalizedString(@"Decrypting Wallet", nil)
#define BC_STRING_LOADING_LOADING_TRANSACTIONS NSLocalizedString(@"Loading transactions", nil)
#define BC_STRING_LOADING_LOADING_BUILD_HD_WALLET NSLocalizedString(@"Initializing Wallet", nil)
#define BC_STRING_LOADING_CHECKING_WALLET_UPDATES NSLocalizedString(@"Checking for Wallet updates", nil)
#define BC_STRING_LOADING_CREATING_V3_WALLET NSLocalizedString(@"Creating V3 Wallet", nil)
#define BC_STRING_LOADING_CREATING NSLocalizedString(@"Creating", nil)
#define BC_STRING_LOADING_CREATING_WALLET NSLocalizedString(@"Creating new Wallet", nil)
#define BC_STRING_LOADING_CREATING_NEW_ADDRESS NSLocalizedString(@"Creating new address", nil)
#define BC_STRING_LOADING_CREATING_REQUEST NSLocalizedString(@"Creating request", nil)
#define BC_STRING_LOADING_CREATING_INVITATION NSLocalizedString(@"Creating invitation", nil)
#define BC_STRING_IDENTIFIER NSLocalizedString(@"Identifier", nil)

#define BC_STRING_SUPPORT NSLocalizedString(@"Support", nil)
#define BC_STRING_OPEN_ARGUMENT NSLocalizedString(@"Open %@?", nil)
#define BC_STRING_LEAVE_APP NSLocalizedString(@"You will be leaving the app.", nil)

#define BC_STRING_TERMS_OF_SERVICE NSLocalizedString(@"Terms of Service", nil)
#define BC_STRING_TRANSACTION NSLocalizedString(@"Transaction", nil)
#define BC_STRING_AUTOMATIC_PAIRING NSLocalizedString(@"Automatic Pairing", nil)
#define BC_STRING_INCORRECT_PASSWORD NSLocalizedString(@"Incorrect password", nil)
#define BC_STRING_CREATE_A_WALLET NSLocalizedString(@"Create a Wallet", nil)
#define BC_STRING_REQUEST_AMOUNT NSLocalizedString(@"Request Amount", nil)
#define BC_STRING_REQUEST NSLocalizedString(@"Request", nil)
#define BC_STRING_REQUEST_PAYMENT NSLocalizedString(@"Request Payment", nil)
#define BC_STRING_LABEL_ADDRESS NSLocalizedString(@"Label Address", nil)
#define BC_STRING_SCAN_PRIVATE_KEY NSLocalizedString(@"Scan Private Key", nil)
#define BC_STRING_IMPORT_ADDRESS NSLocalizedString(@"Import address", nil)
#define BC_STRING_CONTINUE NSLocalizedString(@"Continue", nil)

#define BC_STRING_LOG_IN NSLocalizedString(@"Log In", nil)
#define BC_STRING_PASSWORD_MODAL_INSTRUCTIONS NSLocalizedString(@"Please enter your password to log into your Blockchain wallet.", nil)
#define BC_STRING_OR_START_OVER_AND NSLocalizedString(@"Or start over and ", nil)

#define BC_STRING_COPY_ADDRESS NSLocalizedString(@"Copy Address", nil)
#define BC_STRING_ARCHIVE_ADDRESS NSLocalizedString(@"Archive Address", nil)
#define BC_STRING_UNARCHIVE_ADDRESS NSLocalizedString(@"Unarchive Address", nil)

#define BC_STRING_AT_LEAST_ONE_ACTIVE_ADDRESS NSLocalizedString(@"You must leave at least one active address", nil)

#define BC_STRING_LOGOUT_AND_FORGET_WALLET NSLocalizedString(@"Logout and forget wallet", nil)

#define BC_STRING_SURVEY_ALERT_TITLE NSLocalizedString(@"Would you like to tell us about your experience with Blockchain?", nil)
#define BC_STRING_SURVEY_ALERT_MESSAGE NSLocalizedString(@"You will be leaving the app.", nil)

#define BC_STRING_INVALID_BITCOIN_ADDRESS_ARGUMENT NSLocalizedString(@"Invalid Bitcoin address: %@", nil)
#define BC_STRING_INVALID_ETHER_ADDRESS_ARGUMENT NSLocalizedString(@"Invalid Ether address: %@", nil)

#define BC_STRING_UPDATE NSLocalizedString(@"Update", nil)
#define BC_STRING_DISABLED NSLocalizedString(@"Disabled", nil)
#define BC_STRING_REMINDER_CHECK_EMAIL_TITLE NSLocalizedString(@"Check Your Inbox", nil)
#define BC_STRING_CONTINUE_TO_MAIL NSLocalizedString(@"Continue To Mail", nil)
#define BC_STRING_REMINDER_CHECK_EMAIL_MESSAGE NSLocalizedString(@"Look for an email from Blockchain and click the verification link to complete your wallet setup.", nil)
#define BC_STRING_REMINDER_BACKUP_TITLE NSLocalizedString(@"Backup Your Funds", nil)
#define BC_STRING_REMINDER_BACKUP_NOW NSLocalizedString(@"Backup Now", nil)
#define BC_STRING_REMINDER_TWO_FACTOR_TITLE NSLocalizedString(@"2-Step Verification", nil)
#define BC_STRING_REMINDER_TWO_FACTOR_MESSAGE NSLocalizedString(@"Prevent unauthorized access to your wallet. Enable 2-step verification to increase wallet security.", nil)
#define BC_STRING_SETTINGS_ACCOUNT_DETAILS NSLocalizedString(@"Account Details", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS NSLocalizedString(@"Notifications", nil)
#define BC_STRING_SETTINGS_EMAIL NSLocalizedString(@"Email", nil)
#define BC_STRING_SETTINGS_UPDATE_EMAIL NSLocalizedString(@"Update Email", nil)
#define BC_STRING_SETTINGS_ENTER_EMAIL_ADDRESS NSLocalizedString(@"Enter Email Address", nil)
#define BC_STRING_SETTINGS_VERIFIED NSLocalizedString(@"Verified", nil)
#define BC_STRING_SETTINGS_UNVERIFIED NSLocalizedString(@"Unverified", nil)
#define BC_STRING_SETTINGS_UNCONFIRMED NSLocalizedString(@"Unconfirmed", nil)
#define BC_STRING_SETTINGS_STORED NSLocalizedString(@"Stored", nil)
#define BC_STRING_SETTINGS_NOT_STORED NSLocalizedString(@"Not Stored", nil)
#define BC_STRING_SETTINGS_PLEASE_ADD_EMAIL NSLocalizedString(@"Please add an email address", nil)
#define BC_STRING_SETTINGS_NEW_EMAIL_MUST_BE_DIFFERENT NSLocalizedString(@"New email must be different", nil)
#define BC_STRING_SETTINGS_MOBILE_NUMBER NSLocalizedString(@"Mobile Number", nil)
#define BC_STRING_SETTINGS_UPDATE_MOBILE NSLocalizedString(@"Update Mobile", nil)
#define BC_STRING_SETTINGS_ENTER_MOBILE_NUMBER NSLocalizedString(@"Enter Mobile Number", nil)
#define BC_STRING_SETTINGS_PREFERENCES NSLocalizedString(@"Preferences", nil)
#define BC_STRING_SETTINGS_DISPLAY_PREFERENCES NSLocalizedString(@"Display", nil)
#define BC_STRING_SETTINGS_FEES NSLocalizedString(@"Fees", nil)
#define BC_STRING_SETTINGS_FEE_PER_KB NSLocalizedString(@"Fee per KB", nil)
#define BC_STRING_SETTINGS_SECURITY NSLocalizedString(@"Security", nil)
#define BC_STRING_SETTINGS_PIN_SWIPE_TO_RECEIVE NSLocalizedString(@"Swipe to Receive", nil)
#define BC_STRING_SWIPE_TO_RECEIVE_NO_INTERNET_CONNECTION_WARNING NSLocalizedString(@"We can't check whether this address has been used. Show anyway?", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION NSLocalizedString(@"2-step Verification", nil)
#define BC_STRING_ENABLE NSLocalizedString(@"Enable", nil)
#define BC_STRING_DISABLE NSLocalizedString(@"Disable", nil)
#define BC_STRING_SETTINGS_SECURITY_MUST_DISABLE_TWO_FACTOR_SMS_ARGUMENT NSLocalizedString(@"You must disable SMS 2-Step Verification before changing your mobile number (%@).", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_ENABLED_ARGUMENT NSLocalizedString(@"2-step Verification is currently enabled for %@.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_ENABLED NSLocalizedString(@"2-step Verification is currently enabled.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_DISABLED NSLocalizedString(@"2-step Verification is currently disabled.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_MESSAGE_SMS_ONLY NSLocalizedString(@"You can enable 2-step Verification via SMS on your mobile phone. In order to use other authentication methods instead, please login to our web wallet.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_GOOGLE NSLocalizedString(@"Google Authenticator", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_YUBI_KEY NSLocalizedString(@"Yubi Key", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_SMS NSLocalizedString(@"SMS", nil)
#define BC_STRING_UNKNOWN NSLocalizedString(@"Unknown", nil)
#define BC_STRING_ENTER_ARGUMENT_TWO_FACTOR_CODE NSLocalizedString(@"Please enter your %@ 2FA code", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD NSLocalizedString(@"Change Password", nil)
#define BC_STRING_SETTINGS_SECURITY_PASSWORD_CHANGED NSLocalizedString(@"Password changed. Please login to continue.", nil)
#define BC_STRING_SETTINGS_LOCAL_CURRENCY NSLocalizedString(@"Local Currency", nil)
#define BC_STRING_SETTINGS_BTC NSLocalizedString(@"Bitcoin Unit", nil)
#define BC_STRING_SETTINGS_EMAIL_NOTIFICATIONS NSLocalizedString(@"Email Notifications", nil)
#define BC_STRING_SETTINGS_SMS_NOTIFICATIONS NSLocalizedString(@"SMS Notifications", nil)
#define BC_STRING_SETTINGS_PUSH_NOTIFICATIONS NSLocalizedString(@"Push Notifications", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS_SMS NSLocalizedString(@"SMS", nil)
#define BC_STRING_SETTINGS_EMAIL_PROMPT NSLocalizedString(@"Your verified email address is used to send payment alerts, ID reminders, and login codes.", nil)
#define BC_STRING_SETTINGS_SMS_PROMPT NSLocalizedString(@"Your mobile phone can be used to enable two-factor authentication or to receive alerts.", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS_FOOTER NSLocalizedString(@"Enable notifications to receive an email or SMS message whenever you receive bitcoin.", nil)
#define BC_STRING_SETTINGS_SWIPE_TO_RECEIVE_IN_FIVES_FOOTER NSLocalizedString(@"Enable this option to reveal a receive address when you swipe left on the PIN screen, making receiving bitcoin even faster. Five addresses will be loaded consecutively, after which logging in is required to show new addresses.", nil)
#define BC_STRING_SETTINGS_SWIPE_TO_RECEVE_IN_SINGLES_FOOTER NSLocalizedString(@"Enable this option to reveal a receive address when you swipe left on the PIN screen, making receiving bitcoin even faster. Only one address will be loaded, logging in is required to show a new address.", nil)
#define BC_STRING_SETTINGS_ABOUT NSLocalizedString(@"About", nil)
#define BC_STRING_SETTINGS_ABOUT_US NSLocalizedString(@"About Us", nil)
#define BC_STRING_SETTINGS_PRIVACY_POLICY NSLocalizedString(@"Privacy Policy", nil)
#define BC_STRING_SETTINGS_TERMS_OF_SERVICE NSLocalizedString(@"Terms of Service", nil)
#define BC_STRING_SETTINGS_COOKIE_POLICY NSLocalizedString(@"Cookies Policy", nil)
#define BC_STRING_SETTINGS_VERIFY NSLocalizedString(@"Verify", nil)
#define BC_STRING_SETTINGS_SENT_TO_ARGUMENT NSLocalizedString(@"Sent to %@", nil)
#define BC_STRING_SETTINGS_VERIFY_MOBILE_SEND NSLocalizedString(@"Send verification SMS", nil)
#define BC_STRING_SETTINGS_VERIFY_MOBILE_RESEND NSLocalizedString(@"Resend verification SMS", nil)
#define BC_STRING_SETTINGS_VERIFY_ENTER_CODE NSLocalizedString(@"Enter your verification code", nil)
#define BC_STRING_ENTER_VERIFICATION_CODE NSLocalizedString(@"Enter Verification Code", nil)
#define BC_STRING_SETTINGS_VERIFY_EMAIL_RESEND NSLocalizedString(@"Resend verification email", nil)
#define BC_STRING_SETTINGS_VERIFY_INVALID_CODE NSLocalizedString(@"Invalid verification code. Please try again.", nil)
#define BC_STRING_SETTINGS_CHANGE_EMAIL NSLocalizedString(@"Change Email", nil)
#define BC_STRING_SETTINGS_NEW_EMAIL_ADDRESS NSLocalizedString(@"New Email Address", nil)
#define BC_STRING_SETTINGS_NEW_EMAIL_ADDRESS_WARNING_DISABLE_NOTIFICATIONS NSLocalizedString(@"You currently have email notifications enabled. Changing your email will disable email notifications.", nil)
#define BC_STRING_SETTINGS_EMAIL_VERIFIED NSLocalizedString(@"Your email has been verified.", nil)
#define BC_STRING_SETTINGS_WALLET_ID NSLocalizedString (@"Wallet ID", nil)
#define BC_STRING_SETTINGS_PROFILE NSLocalizedString (@"Profile", nil)
#define BC_STRING_SETTINGS_CHANGE_MOBILE_NUMBER NSLocalizedString(@"Change Mobile Number", nil)
#define BC_STRING_SETTINGS_NEW_MOBILE_NUMBER NSLocalizedString(@"New Mobile Number", nil)
#define BC_STRING_SETTINGS_NEW_MOBILE_NUMBER_WARNING_DISABLE_NOTIFICATIONS NSLocalizedString(@"You currently have SMS notifications enabled. Changing your email will disable SMS notifications.", nil)
#define BC_STRING_SETTINGS_ERROR_INVALID_MOBILE_NUMBER NSLocalizedString(@"Invalid mobile number.", nil)
#define BC_STRING_SETTINGS_MOBILE_NUMBER_VERIFIED NSLocalizedString(@"Your mobile number has been verified.", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_TITLE NSLocalizedString(@"Error loading settings", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_MESSAGE NSLocalizedString(@"Please check your internet connection.", nil)
#define BC_STRING_SETTINGS_ERROR_UPDATING_TITLE NSLocalizedString(@"Error updating settings", nil)
#define BC_STRING_SETTINGS_CHANGE_FEE_TITLE NSLocalizedString(@"Change fee per kilobyte", nil)
#define BC_STRING_SETTINGS_CHANGE_FEE_MESSAGE_ARGUMENT NSLocalizedString(@"Current rate: %@ BTC", nil)
#define BC_STRING_SETTINGS_FEE_ARGUMENT_BTC NSLocalizedString(@"%@ BTC", nil)
#define BC_STRING_SETTINGS_FEE_TOO_HIGH NSLocalizedString(@"Fee is too high (0.01 BTC limit)", nil)
#define BC_STRING_SETTINGS_COPY_GUID NSLocalizedString(@"Copy Wallet ID", nil)
#define BC_STRING_SETTINGS_COPY_GUID_WARNING NSLocalizedString(@"Warning: Your wallet identifier is sensitive information. Copying it may compromise the security of your wallet.", nil)
#define BC_STRING_COPY_TO_CLIPBOARD NSLocalizedString(@"Copy to clipboard", nil)
#define BC_STRING_WARNING_FOR_ZERO_FEE NSLocalizedString(@"Transactions with no fees may take a long time to confirm or may not be confirmed at all. Would you like to continue?", nil)
#define BC_STRING_SETTINGS_ERROR_FEE_OUT_OF_RANGE NSLocalizedString(@"Please enter a fee greater than 0 BTC and at most 0.01 BTC", nil)

#define BC_STRING_VERIFY_EMAIL NSLocalizedString(@"Verify Email", nil)
#define BC_STRING_EMAIL_VERIFIED NSLocalizedString(@"Email Verified", nil)
#define BC_STRING_BACKUP_PHRASE NSLocalizedString(@"Backup Phrase", nil)
#define BC_STRING_WALLET_RECOVERY_PHRASE NSLocalizedString(@"Recovery Phrase", nil)
#define BC_STRING_PHRASE_BACKED NSLocalizedString(@"Phrase Backed", nil)
#define BC_STRING_LINK_MOBILE NSLocalizedString(@"Link Mobile", nil)
#define BC_STRING_MOBILE_LINKED NSLocalizedString(@"Mobile Linked", nil)
#define BC_STRING_TWO_STEP_ENABLED_SUCCESS NSLocalizedString(@"2-Step has been enabled for SMS.", nil)
#define BC_STRING_TWO_STEP_DISABLED_SUCCESS NSLocalizedString(@"2-Step has been disabled.", nil)
#define BC_STRING_TWO_STEP_ERROR NSLocalizedString(@"An error occurred while changing 2-Step verification.", nil)
#define BC_STRING_TWO_STEP_ENABLED NSLocalizedString(@"2-Step Enabled", nil)
#define BC_STRING_ENABLE_TWO_STEP NSLocalizedString(@"Enable 2-Step", nil)
#define BC_STRING_ENABLE_TWO_STEP_SMS NSLocalizedString(@"Enable 2-Step for SMS", nil)

#define BC_STRING_NEW_ADDRESS NSLocalizedString(@"New Address", nil)
#define BC_STRING_NEW_ADDRESS_SCAN_QR_CODE NSLocalizedString(@"Scan QR code", nil)
#define BC_STRING_NEW_ADDRESS_CREATE_NEW NSLocalizedString(@"Create new address", nil)

#define BC_STRING_SEARCH NSLocalizedString(@"Search", nil)
#define BC_STRING_TOTAL NSLocalizedString(@"Total", nil)
#define BC_STRING_SENDING NSLocalizedString(@"Sending", nil)

#define BC_STRING_RECOVERY_PHRASE_ERROR_INSTRUCTIONS NSLocalizedString(@"Please enter your recovery phrase with words separated by spaces", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET NSLocalizedString(@"Recovering Funds", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_CHECKING_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Checking for more: Step %d of %d", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_ARGUMENT_FUNDS_ARGUMENT NSLocalizedString(@"Found %d, with %@", nil)
#define BC_STRING_LOADING_RECOVERY_CREATING_WALLET NSLocalizedString(@"Creating Wallet", nil)
#define BC_STRING_INVALID_RECOVERY_PHRASE NSLocalizedString(@"Invalid recovery phrase. Please try again", nil)

#define BC_STRING_SEND_ERROR_NO_INTERNET_CONNECTION NSLocalizedString(@"No internet connection available. Please check your network settings.", nil)
#define BC_STRING_SEND_ERROR_FEE_TOO_LOW NSLocalizedString(@"The fee you have specified is too low.", nil)
#define BC_STRING_HIGH_FEE_WARNING_TITLE NSLocalizedString(@"Large Transaction", nil)
#define BC_STRING_HIGH_FEE_WARNING_MESSAGE NSLocalizedString(@"This is an oversized bitcoin transaction. Your wallet needs to consolidate many smaller payments you've received in the past. This requires a relatively high fee in order to be confirmed quickly. If it’s fine for the transaction to take longer to confirm, you can reduce the fee manually by tapping \"Customize Fee.\"", nil)
#define BC_STRING_NO_EMAIL_CONFIGURED NSLocalizedString(@"You do not have an account set up for Mail. Please contact %@", nil)

#define BC_STRING_NO_EMAIL_CONFIGURED NSLocalizedString(@"You do not have an account set up for Mail. Please contact %@", nil)
#define BC_STRING_PIN NSLocalizedString(@"PIN", nil)

#define BC_STRING_MAKE_DEFAULT NSLocalizedString(@"Make Default", nil)
#define BC_STRING_DEFAULT NSLocalizedString(@"Default", nil)
#define BC_STRING_TRANSFER_FUNDS NSLocalizedString(@"Transfer Funds", nil)
#define BC_STRING_TRANSFER_AMOUNT NSLocalizedString(@"Transfer Amount", nil)
#define BC_STRING_FEE NSLocalizedString(@"Fee", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_ONE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_TWO NSLocalizedString(@"Your transferred funds will be safe and secure, and you'll benefit from increased privacy and convenient backup and recovery features.", nil)
#define BC_STRING_ARCHIVE_FOOTER_TITLE NSLocalizedString(@"Archive this if you do NOT want to use it anymore. Your funds will remain safe, and you can unarchive it at any time.", nil)
#define BC_STRING_ARCHIVED_FOOTER_TITLE NSLocalizedString(@"This is archived. Though you cannot send funds from here, any and all funds will remain safe. Simply unarchive to start using it again.", nil)
#define BC_STRING_TRANSFER_FOOTER_TITLE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_FOOTER_TITLE NSLocalizedString(@"Keep your xPub private. Someone with access to your xPub will be able to see all of your funds and transactions.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_WARNING NSLocalizedString(@"Sharing your xPub authorizes others to track your transaction history. As authorized persons may be able to disrupt you from accessing your wallet, only share your xPub with people you trust.", nil)
#define BC_STRING_WATCH_ONLY_FOOTER_TITLE NSLocalizedString(@"This is a watch-only address. To spend your funds from this wallet, please scan your private key.", nil)
#define BC_STRING_SET_DEFAULT_ACCOUNT NSLocalizedString(@"Set as Default?", nil)
#define BC_STRING_AT_LEAST_ONE_ADDRESS_REQUIRED NSLocalizedString(@"You must have at least one active address", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_DETAIL_HEADER_TITLE NSLocalizedString(@"Your xPub is an advanced feature that contains all of your public addresses.", nil)
#define BC_STRING_COPY_XPUB NSLocalizedString(@"Copy xPub", nil)
#define BC_STRING_IMPORTED_PRIVATE_KEY_TO_OTHER_ADDRESS_ARGUMENT NSLocalizedString(@"You've successfully imported the private key for ​the address %@, and you can now spend from it. If you want to spend from this address, make sure you scan the correct private key.", nil)
#define BC_STRING_VERIFICATION_EMAIL_SENT_TO_ARGUMENT NSLocalizedString(@"Verification email has been sent to %@.", nil)
#define BC_STRING_PLEASE_CHECK_AND_CLICK_EMAIL_VERIFICATION_LINK NSLocalizedString(@"Please check your email and click on the verification link.", nil)
#define BC_STRING_ERROR_PLEASE_REFRESH_PAIRING_CODE NSLocalizedString(@"Please refresh the pairing code and try again.", nil)

#define BC_STRING_NOT_NOW NSLocalizedString(@"Not Now", nil)
#define BC_STRING_ILL_DO_THIS_LATER NSLocalizedString(@"I'll do this later", nil)
#define BC_STRING_PRIVATE_KEY_NEEDED_MESSAGE_ARGUMENT NSLocalizedString(@"This action requires the private key for the Bitcoin address %@. Please scan the QR code.", nil)
#define BC_STRING_ENTER_ARGUMENT_AMOUNT NSLocalizedString(@"Enter %@ amount", nil)
#define BC_STRING_RETRIEVING_RECOMMENDED_FEE NSLocalizedString(@"Retrieving recommended fee", nil)
#define BC_STRING_FEE_HIGHER_THAN_RECOMMENDED_ARGUMENT_SUGGESTED_ARGUMENT NSLocalizedString(@"You specified an unusually high transaction fee of %@. Even if you lower the fee to %@, you can expect the transaction to confirm within the next 10 minutes (one block).", nil)
#define BC_STRING_FEE_LOWER_THAN_RECOMMENDED_ARGUMENT_SUGGESTED_ARGUMENT NSLocalizedString(@"You specified an exceptionally small transaction fee of %@. Your transaction may be stuck and possibly never be confirmed. To increase the likelihood for your transaction to confirm within approximately one hour (six blocks), we strongly recommend a fee of no less than %@.", nil)
#define BC_STRING_FEE_LOWER_THAN_RECOMMENDED_ARGUMENT_MUST_LOWER_AMOUNT_SUGGESTED_FEE_ARGUMENT_SUGGESTED_AMOUNT_ARGUMENT NSLocalizedString(@"You specified an exceptionally small transaction fee of %@. Your transaction may become stuck and possibly never confirm. To increase the likelihood for your transaction to confirm within approximately one hour (six blocks), we strongly recommend a fee of no less than %@. Since you don’t have sufficient funds, that means the Send amount will also have to be lowered to %@.", nil)
#define BC_STRING_INCREASE_FEE NSLocalizedString(@"Increase fee", nil)
#define BC_STRING_LOWER_FEE NSLocalizedString(@"Lower fee", nil)
#define BC_STRING_KEEP_HIGHER_FEE NSLocalizedString(@"Keep higher fee", nil)
#define BC_STRING_KEEP_LOWER_FEE NSLocalizedString(@"Keep lower fee", nil)
#define BC_STRING_USE_RECOMMENDED_VALUES NSLocalizedString(@"Use recommended values", nil)
#define BC_STRING_PLEASE_LOWER_CUSTOM_FEE NSLocalizedString(@"Please lower the fee to an amount that is less than your balance", nil)
#define BC_STRING_SURGE_OCCURRING_TITLE NSLocalizedString(@"Surge Occurring", nil)
#define BC_STRING_SURGE_OCCURRING_MESSAGE NSLocalizedString(@"The Bitcoin mining network is currently experiencing a high volume of activity, resulting in recommended fees that are higher than usual.", nil)
#define BC_STRING_FEE_INFORMATION_TITLE NSLocalizedString(@"Transaction Fees", nil)
#define BC_STRING_FEE_INFORMATION_MESSAGE NSLocalizedString(@"Transaction fees impact how quickly the mining network will confirm your transactions, and depend on the current network conditions.", nil)
#define BC_STRING_FEE_INFORMATION_MESSAGE_APPEND_REGULAR_SEND NSLocalizedString (@" We recommend the fee shown for the transaction at this time.", nil)
#define BC_STRING_FEE_INFORMATION_DUST NSLocalizedString(@"This transaction requires a higher fee for dust consumption due to the small amount of change to be returned.", nil)

#define BC_STRING_FEE_INFORMATION_MESSAGE_ETHER NSLocalizedString (@"Miners receive this fee to process this transaction.", nil)

#define BC_STRING_TRANSACTION_DESCRIPTION_PLACEHOLDER NSLocalizedString(@"What's this for?", nil)
#define BC_STRING_NO_DESCRIPTION NSLocalizedString(@"No description", nil)

#define BC_STRING_WHATS_THIS NSLocalizedString(@"What's this?", nil)

#define BC_STRING_BLOCKCHAIN_ALL_RIGHTS_RESERVED NSLocalizedString(@"All rights reserved.", nil)



#define BC_STRING_RATE_US NSLocalizedString(@"Rate us", nil)

#define BC_STRING_ERROR_SAVING_WALLET_CHECK_FOR_OTHER_DEVICES NSLocalizedString(@"An error occurred while saving your changes. Please make sure you are not logged into your wallet on another device.", nil)
#define BC_STRING_ADDRESS_ALREADY_USED_PLEASE_LOGIN NSLocalizedString(@"This address has already been used. Please login.", nil)
#define BC_STRING_PLEASE_LOGIN_TO_LOAD_MORE_ADDRESSES NSLocalizedString(@"Please login to load more addresses.", nil)

#define BC_STRING_ERROR_TICKER NSLocalizedString(@"An error occurred while retrieving currency conversion rates. Please try again later.", nil)
#define BC_STRING_ERROR_CHARTS NSLocalizedString(@"An error occurred while retrieving the latest chart data. Please try again later.", nil)

#define BC_STRING_DESCRIPTION NSLocalizedString(@"Description", nil)
#define BC_STRING_DETAILS NSLocalizedString(@"Details", nil)
#define BC_STRING_VALUE_WHEN_SENT_ARGUMENT NSLocalizedString(@"Value when sent: %@", nil)
#define BC_STRING_VALUE_WHEN_RECEIVED_ARGUMENT NSLocalizedString(@"Value when received: %@", nil)
#define BC_STRING_STATUS NSLocalizedString(@"Status", nil)
#define BC_STRING_CONFIRMED NSLocalizedString(@"Confirmed", nil)
#define BC_STRING_PENDING_ARGUMENT_CONFIRMATIONS NSLocalizedString(@"Pending (%@ Confirmations)", nil)
#define BC_STRING_TRANSACTION_FEE_ARGUMENT NSLocalizedString(@"Transaction fee: %@", nil)
#define BC_STRING_PENDING NSLocalizedString(@"Pending", nil)
#define BC_STRING_DOUBLE_SPEND_WARNING NSLocalizedString(@"May be at risk for a double spend.", nil)
#define BC_STRING_ARGUMENT_RECIPIENTS NSLocalizedString(@"%lu Recipients", nil)
#define BC_STRING_TO NSLocalizedString(@"To", nil)
#define BC_STRING_DATE NSLocalizedString(@"Date", nil)
#define BC_STRING_FROM NSLocalizedString(@"From", nil)
#define BC_STRING_ERROR_GETTING_FIAT_AT_TIME NSLocalizedString(@"Could not get value when sent - please check your internet connection and try again.", nil)
#define BC_STRING_COULD_NOT_FIND_TRANSACTION_ARGUMENT NSLocalizedString(@"Could not find transaction with hash %@ when reloading data", nil)
#define BC_STRING_RECIPIENTS NSLocalizedString(@"Recipients", nil)

#define BC_STRING_US_DOLLAR NSLocalizedString(@"U.S. Dollar", @"")
#define BC_STRING_EURO NSLocalizedString(@"Euro", @"")
#define BC_STRING_ICELANDIC_KRONA NSLocalizedString(@"lcelandic Króna", @"")
#define BC_STRING_HONG_KONG_DOLLAR NSLocalizedString(@"Hong Kong Dollar", @"")
#define BC_STRING_NEW_TAIWAN_DOLLAR NSLocalizedString(@"New Taiwan Dollar", @"")
#define BC_STRING_SWISS_FRANC NSLocalizedString(@"Swiss Franc", @"")
#define BC_STRING_DANISH_KRONE NSLocalizedString(@"Danish Krone", @"")
#define BC_STRING_CHILEAN_PESO NSLocalizedString(@"Chilean Peso", @"")
#define BC_STRING_CANADIAN_DOLLAR NSLocalizedString(@"Canadian Dollar", @"")
#define BC_STRING_INDIAN_RUPEE NSLocalizedString(@"Indian Rupee", @"")
#define BC_STRING_CHINESE_YUAN NSLocalizedString(@"Chinese Yuan", @"")
#define BC_STRING_THAI_BAHT NSLocalizedString(@"Thai Baht", @"")
#define BC_STRING_AUSTRALIAN_DOLLAR NSLocalizedString(@"Australian Dollar", @"")
#define BC_STRING_SINGAPORE_DOLLAR NSLocalizedString(@"Singapore Dollar", @"")
#define BC_STRING_SOUTH_KOREAN_WON NSLocalizedString(@"South Korean Won", @"")
#define BC_STRING_JAPANESE_YEN NSLocalizedString(@"Japanese Yen", @"")
#define BC_STRING_POLISH_ZLOTY NSLocalizedString(@"Polish Zloty", @"")
#define BC_STRING_GREAT_BRITISH_POUND NSLocalizedString(@"Great British Pound", @"")
#define BC_STRING_SWEDISH_KRONA NSLocalizedString(@"Swedish Krona", @"")
#define BC_STRING_NEW_ZEALAND_DOLLAR NSLocalizedString(@"New Zealand Dollar", @"")
#define BC_STRING_BRAZIL_REAL NSLocalizedString(@"Brazil Real", @"")
#define BC_STRING_RUSSIAN_RUBLE NSLocalizedString(@"Russian Ruble", @"")

#define BC_STRING_BALANCES NSLocalizedString(@"Balances", nil)
#define BC_STRING_NO_TRANSACTIONS_TITLE NSLocalizedString(@"No Transactions", nil)
#define BC_STRING_NO_TRANSACTIONS_TEXT_BITCOIN NSLocalizedString(@"Transactions occur when you send and request bitcoin.", nil)
#define BC_STRING_NO_TRANSACTIONS_TEXT_ETHER NSLocalizedString(@"Transactions occur when you send and request ether.", nil)
#define BC_STRING_NO_TRANSACTIONS_TEXT_BITCOIN_CASH NSLocalizedString(@"Transactions occur when you send and request bitcoin cash.", nil)

#define BC_STRING_YOUR_TRANSACTIONS NSLocalizedString(@"Your Transactions", nil)

#define BC_STRING_VIEW_ON_URL_ARGUMENT NSLocalizedString(@"View on", nil)

#pragma mark - Swift files

#define BC_STRING_BACKUP_COMPLETE NSLocalizedString(@"Backup Complete", nil)
#define BC_STRING_BACKUP_NEEDED NSLocalizedString(@"Backup Needed", nil)
#define BC_STRING_BACKUP_COMPLETED_EXPLANATION NSLocalizedString(@"Use your Recovery Phrase to restore your funds in case of a lost password.  Anyone with access to your Recovery Phrase can access your funds, so keep it offline somewhere safe and secure.", nil)
#define BC_STRING_BACKUP_NEEDED_BODY_TEXT_ONE NSLocalizedString(@"The following 12 word Recovery Phrase will give you access to your funds in case you lose your password.", nil)
#define BC_STRING_BACKUP_NEEDED_BODY_TEXT_TWO NSLocalizedString(@"Be sure to write down your phrase on a piece of paper and keep it somewhere safe and secure.", nil)
#define BC_STRING_BACKUP_WORDS_INSTRUCTIONS NSLocalizedString(@"Write down the following 12 word Recovery Phrase exactly as they appear and in this order:", nil)
#define BC_STRING_BACKUP_PREVIOUS NSLocalizedString(@"PREVIOUS", nil)
#define BC_STRING_BACKUP_NEXT NSLocalizedString(@"NEXT", nil)
#define BC_STRING_BACKUP_AGAIN NSLocalizedString(@"BACKUP AGAIN", nil)
#define BC_STRING_TRANSFER_ALL NSLocalizedString(@"Transfer all", nil)
#define BC_STRING_TRANSFER_ALL_FUNDS NSLocalizedString(@"Transfer All Funds", nil)
#define BC_STRING_TRANSFER_IMPORTED_ADDRESSES NSLocalizedString(@"Transfer imported addresses?", nil)
#define BC_STRING_TRANSFER_ALL_BACKUP NSLocalizedString(@"Imported addresses are not backed up by your Recovery Phrase. To secure these funds, we recommend transferring these balances to include in your backup.", nil)

#define BC_STRING_BE_YOUR_OWN_BANK NSLocalizedString (@"Be your own bank", nil)
#define BC_STRING_WELCOME_MESSAGE_ONE NSLocalizedString (@"Welcome to Blockchain", nil)
#define BC_STRING_WELCOME_MESSAGE_TWO NSLocalizedString (@"Securely store bitcoin", nil)
#define BC_STRING_WELCOME_MESSAGE_THREE NSLocalizedString (@"Seamlessly transact with others around the world", nil)
#define BC_STRING_OVERVIEW_MARKET_PRICE_TITLE NSLocalizedString(@"Current Price", nil)
#define BC_STRING_OVERVIEW_MARKET_PRICE_DESCRIPTION NSLocalizedString (@"We work with exchange partners all over the world, so you can buy and sell bitcoin directly from your wallet.", nil)
#define BC_STRING_OVERVIEW_REQUEST_FUNDS_TITLE NSLocalizedString(@"Request Funds", nil)
#define BC_STRING_OVERVIEW_REQUEST_FUNDS_DESCRIPTION NSLocalizedString (@"Send your wallet address to a friend to request funds. An address is a string of random letters and numbers that change for each transaction.", nil)
#define BC_STRING_OVERVIEW_QR_CODES_TITLE NSLocalizedString(@"QR Codes", nil)
#define BC_STRING_OVERVIEW_QR_CODES_DESCRIPTION NSLocalizedString(@"An address can also be shown as a QR code. Scan a friend's QR code to quickly capture their wallet address.", nil)
#define BC_STRING_OVERVIEW_COMPLETE_TITLE NSLocalizedString(@"That's it for now!", nil)
#define BC_STRING_OVERVIEW_COMPLETE_DESCRIPTION NSLocalizedString(@"We'll keep you up-to-date here with recommendations and new features.", nil)
#define BC_STRING_START_OVER NSLocalizedString(@"Start Over", nil)
#define BC_STRING_OPEN_MAIL NSLocalizedString(@"Open Mail", nil)
#define BC_STRING_SCAN_ADDRESS NSLocalizedString(@"Scan Address", nil)
#define BC_STRING_SKIP_ALL NSLocalizedString(@"Skip All", nil)
#define BC_STRING_GET_BITCOIN NSLocalizedString(@"Get Bitcoin", nil)
#define BC_STRING_GET_ETHER NSLocalizedString(@"Get Ether", nil)
#define BC_STRING_REQUEST_ETHER NSLocalizedString(@"Request Ether", nil)
#define BC_STRING_GET_BITCOIN_CASH NSLocalizedString(@"Get Bitcoin Cash", nil)
#define BC_STRING_REQUEST_BITCOIN_CASH NSLocalizedString(@"Request Bitcoin Cash", nil)
#define BC_STRING_OVERVIEW NSLocalizedString(@"Overview", nil)
#define BC_STRING_DASHBOARD NSLocalizedString(@"Dashboard", nil)

#define BC_STRING_ENABLED_EXCLAMATION NSLocalizedString(@"Enabled!", nil)

#define BC_STRING_CUSTOM NSLocalizedString(@"Custom", nil)
#define BC_STRING_ADVANCED_USERS_ONLY NSLocalizedString(@"Advanced users only", nil)
#define BC_STRING_REGULAR BC_STRING_PASSWORD_STRENGTH_REGULAR
#define BC_STRING_GREATER_THAN_ONE_HOUR NSLocalizedString(@"1+ hour", nil)
#define BC_STRING_PRIORITY NSLocalizedString(@"Priority", nil)
#define BC_STRING_LESS_THAN_ONE_HOUR NSLocalizedString(@"~0-60 min", nil)
#define BC_STRING_SATOSHI_PER_BYTE NSLocalizedString(@"Satoshi per byte", nil)
#define BC_STRING_SATOSHI_PER_BYTE_ABBREVIATED NSLocalizedString(@"sat/b", nil)
#define BC_STRING_HIGH_FEE_NOT_NECESSARY NSLocalizedString(@"High fee not necessary", nil)
#define BC_STRING_LOW_FEE_NOT_RECOMMENDED NSLocalizedString(@"Low fee not recommended", nil)
#define BC_STRING_NOT_ENOUGH_FUNDS_TO_USE_FEE NSLocalizedString(@"You do not have enough funds to use this fee.", nil)
#define BC_STRING_CUSTOM_FEE_WARNING NSLocalizedString(@"This feature is recommended for advanced users only. By choosing a custom fee, you risk overpaying or your transaction may get stuck.", nil)

#define BC_STRING_AVAILABLE_NOW_TITLE NSLocalizedString(@"Available now", nil)
#define BC_STRING_BUY_SELL_NOT_SUPPORTED_IOS_8_WEB_LOGIN NSLocalizedString(@"Mobile Buy & Sell is supported for iOS 9 and up. Please run a software update or login at login.blockchain.com on your computer.", nil)

#define BC_STRING_LOG_IN_TO_WEB_WALLET NSLocalizedString(@"Log in to Web Wallet", nil)
#define BC_STRING_WEB_LOGIN_INSTRUCTION_STEP_ONE NSLocalizedString(@"Go to login.blockchain.com on your computer.", nil)
#define BC_STRING_WEB_LOGIN_INSTRUCTION_STEP_TWO NSLocalizedString(@"Select Log in via mobile.", nil)
#define BC_STRING_WEB_LOGIN_INSTRUCTION_STEP_THREE NSLocalizedString(@"Using your computer's camera, scan the QR code below.", nil)
#define BC_STRING_WEB_LOGIN_QR_INSTRUCTION_LABEL_HIDDEN NSLocalizedString(@"Keep this QR code hidden until you're ready.", nil)
#define BC_STRING_WEB_LOGIN_QR_INSTRUCTION_LABEL_SHOWN_ONE NSLocalizedString(@"Keep this QR code safe!", nil)
#define BC_STRING_WEB_LOGIN_QR_INSTRUCTION_LABEL_SHOWN_TWO NSLocalizedString(@"Do not share it with others.", nil)
#define BC_STRING_SHOW_QR_CODE NSLocalizedString(@"Show QR Code", nil)
#define BC_STRING_HIDE_QR_CODE NSLocalizedString(@"Hide QR Code", nil)

#define BC_STRING_DAY NSLocalizedString(@"Day", nil)
#define BC_STRING_WEEK NSLocalizedString(@"Week", nil)
#define BC_STRING_MONTH NSLocalizedString(@"Month", nil)
#define BC_STRING_YEAR NSLocalizedString(@"Year", nil)
#define BC_STRING_ALL NSLocalizedString(@"All", nil)

#define BC_STRING_AT NSLocalizedString(@"at", nil)
#define BC_STRING_BITCOIN_PRICE NSLocalizedString(@"Bitcoin Price", nil)
#define BC_STRING_ETHER_PRICE NSLocalizedString(@"Ether Price", nil)
#define BC_STRING_CONTRACT_ADDRESSES_NOT_SUPPORTED_TITLE NSLocalizedString(@"Contract addresses are not supported.", nil)
#define BC_STRING_CONTRACT_ADDRESSES_NOT_SUPPORTED_MESSAGE NSLocalizedString(@"At the moment we only support ETH. You cannot receive REP, ICN, GNT, GNO, DGD, BCP.", nil)
#define BC_STRING_RECEIVE_ETHER_REENTER_SECOND_PASSWORD_INSTRUCTIONS NSLocalizedString(@"Tap the Request tab to setup your ether address.", nil)

#define BC_STRING_NOW_SUPPORTING_ETHER_TITLE NSLocalizedString(@"Now supporting Ether", nil)
#define BC_STRING_NOW_SUPPORTING_ETHER_DESCRIPTION NSLocalizedString(@"You asked, we listened. We’re excited to announce that your Blockchain wallet will now allow you to seamlessly send and receive ether!", nil)
#define BC_STRING_GET_STARTED_WITH_ETHER NSLocalizedString(@"Get Started with Ether", nil)

#define BC_STRING_EXCHANGE NSLocalizedString(@"Exchange", nil)
#define BC_STRING_NEW_EXCHANGE NSLocalizedString(@"New Exchange", nil)
#define BC_STRING_USE_MINIMUM NSLocalizedString(@"Use minimum", nil)
#define BC_STRING_USE_MAXIMUM NSLocalizedString(@"Use maximum", nil)
#define BC_STRING_EXCHANGE_TITLE_SENDING_FUNDS NSLocalizedString(@"Sending Funds", nil)
#define BC_STRING_EXCHANGE_DESCRIPTION_SENDING_FUNDS NSLocalizedString(@"Thanks for placing your trade!  Exchange trades can take up to two hours, and you can keep track of your trade’s progress in the Order History section.", nil)
#define BC_STRING_IN_PROGRESS NSLocalizedString(@"In Progress", nil)
#define BC_STRING_EXCHANGE_DESCRIPTION_IN_PROGRESS NSLocalizedString(@"Exchanges can take up to two hours, you can keep track of your exchange progress in the Order History. Once the trade is complete, your ether will arrive in your wallet.", nil)
#define BC_STRING_EXCHANGE_DESCRIPTION_CANCELED NSLocalizedString(@"Your trade has been canceled. Please return to the exchange tab to start your trade again.", nil)
#define BC_STRING_FAILED NSLocalizedString(@"Failed", nil)
#define BC_STRING_EXCHANGE_TITLE_REFUNDED NSLocalizedString(@"Trade Refunded", nil)
#define BC_STRING_EXCHANGE_DESCRIPTION_FAILED NSLocalizedString(@"This trade has failed. Any funds sent from your wallet will be returned minus the transaction fee. Please return to the exchange tab to start a new trade.", nil)
#define BC_STRING_EXCHANGE_DESCRIPTION_EXPIRED NSLocalizedString(@"Your trade has expired. Please return to the exchange tab to start a new trade.", nil)
#define BC_STRING_EXCHANGE_CARD_DESCRIPTION NSLocalizedString(@"You can now exchange your bitcoin for ether and vice versa directly from your Blockchain wallet!", nil)
#define BC_STRING_ARGUMENT_TO_DEPOSIT NSLocalizedString(@"%@ to Deposit", nil)
#define BC_STRING_ARGUMENT_TO_BE_RECEIVED NSLocalizedString(@"%@ to be Received", nil)
#define BC_STRING_EXCHANGE_RATE NSLocalizedString(@"Exchange Rate", nil)
#define BC_STRING_TRANSACTION_FEE NSLocalizedString(@"Transaction Fee", nil)
#define BC_STRING_NETWORK_TRANSACTION_FEE NSLocalizedString(@"Network Transaction Fee", nil)
#define BC_STRING_SHAPESHIFT_WITHDRAWAL_FEE NSLocalizedString(@"ShapeShift Withdrawal Fee", nil)
#define BC_STRING_AGREE_TO_SHAPESHIFT NSLocalizedString(@"Agree to ShapeShift", nil)
#define BC_STRING_TERMS_AND_CONDITIONS NSLocalizedString(@"terms and conditions", nil)
#define BC_STRING_EXCHANGE_IN_PROGRESS NSLocalizedString(@"Exchange In Progress", nil)
#define BC_STRING_EXCHANGE_COMPLETED NSLocalizedString(@"Exchange Completed", nil)
#define BC_STRING_GET_STARTED NSLocalizedString(@"Get started", nil)
#define BC_STRING_BELOW_MINIMUM_LIMIT NSLocalizedString(@"Below minimum limit", nil)
#define BC_STRING_ABOVE_MAXIMUM_LIMIT NSLocalizedString(@"Above maximum limit", nil)
#define BC_STRING_NOT_ENOUGH_TO_EXCHANGE NSLocalizedString(@"Not enough to exchange", nil)
#define BC_STRING_EXCHANGE_ORDER_ID NSLocalizedString(@"Order ID", nil)
#define BC_STRING_TOTAL_ARGUMENT_SPENT NSLocalizedString(@"Total %@ spent", nil)
#define BC_STRING_GETTING_QUOTE NSLocalizedString(@"Getting quote", nil)
#define BC_STRING_CONFIRMING NSLocalizedString(@"Confirming", nil)
#define BC_STRING_EXCHANGE_IN_PROGRESS NSLocalizedString(@"Exchange In Progress", nil)
#define BC_STRING_COMPLETE NSLocalizedString(@"Complete", nil)
#define BC_STRING_EXCHANGE_COMPLETED NSLocalizedString(@"Exchange Completed", nil)
#define BC_STRING_QUOTE_EXIRES_IN_ARGUMENT NSLocalizedString(@"Quote expires in %@", nil)
#define BC_STRING_STEP_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Step %d of %d", nil)
#define BC_STRING_SELECT_YOUR_STATE NSLocalizedString(@"Select your State:", nil)
#define BC_STRING_SELECT_STATE NSLocalizedString(@"Select State", nil)
#define BC_STRING_EXCHANGE_NOT_AVAILABLE_TITLE NSLocalizedString(@"Not Available", nil)
#define BC_STRING_EXCHANGE_NOT_AVAILABLE_MESSAGE NSLocalizedString(@"Exchanging coins is not yet available in your state. We’ll be rolling out more states soon.", nil)
#define BC_STRING_ERROR_GETTING_BALANCE_ARGUMENT_ASSET_ARGUMENT_MESSAGE NSLocalizedString(@"An error occurred when getting your %@ balance. Please try again later. Details: %@", nil)
#define BC_STRING_ERROR_GETTING_APPROXIMATE_QUOTE_ARGUMENT_MESSAGE NSLocalizedString(@"An error occurred when getting an approximate quote. Please try again later. Details: %@", nil)
#define BC_STRING_DEPOSITED_TO_SHAPESHIFT NSLocalizedString(@"Deposited to ShapeShift", nil)
#define BC_STRING_RECEIVED_FROM_SHAPESHIFT NSLocalizedString(@"Received from ShapeShift", nil)
#define BC_STRING_ORDER_HISTORY NSLocalizedString(@"Order History", nil)
#define BC_STRING_INCOMING NSLocalizedString(@"Incoming", nil)
#define BC_STRING_TRADE_EXPIRED_TITLE NSLocalizedString(@"Trade Expired", nil)
#define BC_STRING_TRADE_EXPIRED_MESSAGE NSLocalizedString(@"Your trade has expired. Please return to the Exchange page to start your trade again.", nil)
#define BC_STRING_NO_FUNDS_TO_EXCHANGE_TITLE NSLocalizedString(@"No Funds to Exchange", nil)
#define BC_STRING_NO_FUNDS_TO_EXCHANGE_MESSAGE NSLocalizedString(@"You have no funds to exchange. Why not get started by receiving some funds?", nil)
#define BC_STRING_SELECT_ARGUMENT_WALLET NSLocalizedString(@"Select other %@ Wallet", nil)
#define BC_STRING_ARGUMENT_NEEDED_TO_EXCHANGE NSLocalizedString(@"%@ needed to exchange", nil)
#define BC_STRING_FAILED_TO_LOAD_EXCHANGE_DATA NSLocalizedString(@"Failed to load exchange data", nil)

#define BC_STRING_BUY_SELL_CARD_TITLE NSLocalizedString(@"The wait is over", nil)

#define BC_STRING_PRICE NSLocalizedString(@"Price", nil)
#define BC_STRING_SEE_CHARTS NSLocalizedString(@"See charts", nil)
#define BC_STRING_PRICE_CHARTS NSLocalizedString(@"Price charts", nil)

#define BC_STRING_BITCOIN_CASH_PRICE NSLocalizedString(@"Bitcoin Cash Price", nil)
#define BC_STRING_ENTER_BITCOIN_CASH_ADDRESS_OR_SELECT NSLocalizedString(@"Enter Bitcoin Cash address or select", nil)
#define BC_STRING_BUY_SELL_CARD_DESCRIPTION NSLocalizedString(@"Buy and sell bitcoin directly from your Blockchain wallet. Start by creating an account in the Buy & Sell tab.", nil)
#define BC_STRING_BUY_SELL_CARD_ACTION_TITLE BC_STRING_GET_STARTED

#define BC_STRING_BITCOIN_CASH_WARNING_CONFIRM_VALID_ADDRESS_ONE NSLocalizedString(@"Are you sure this is a bitcoin cash address?", nil)
#define BC_STRING_BITCOIN_CASH_WARNING_CONFIRM_VALID_ADDRESS_TWO NSLocalizedString(@"Sending funds to a bitcoin address by accident will result in loss of funds.", nil)

#define BC_STRING_COPY_WARNING_TEXT NSLocalizedString(@"Copy this receive address to the clipboard? If so, be advised that other applications may be able to look at this information.", nil)
