// Generated by Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import AVFoundation;
@import CoreGraphics;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Veriff",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif




SWIFT_CLASS("_TtC6Veriff12BundleBridge")
@interface BundleBridge : NSObject
+ (void)setLanguageWithIso:(NSString * _Nonnull)iso;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol DeviceCameraAccess;
@class AVCaptureVideoPreviewLayer;

SWIFT_CLASS("_TtC6Veriff12DeviceCamera")
@interface DeviceCamera : NSObject <AVCapturePhotoCaptureDelegate, AVCaptureVideoDataOutputSampleBufferDelegate>
+ (DeviceCamera * _Nonnull)createCameraWithDelegate:(id <DeviceCameraAccess> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
- (void)startRunning;
- (void)stopRunning;
- (void)setWithDelegate:(id <DeviceCameraAccess> _Nonnull)delegate;
- (AVCaptureVideoPreviewLayer * _Nonnull)getPreviewLayer SWIFT_WARN_UNUSED_RESULT;
- (void)switchCamera;
- (void)switchToBackCamera;
- (void)capturePhoto;
- (void)enableFlash;
- (void)disableFlash;
- (void)grantCameraPermission;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class AVCapturePhotoOutput;
@class AVCaptureResolvedPhotoSettings;
@class AVCaptureBracketedStillImageSettings;
@class AVCaptureOutput;
@class AVCaptureConnection;

@interface DeviceCamera (SWIFT_EXTENSION(Veriff))
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhotoSampleBuffer:(CMSampleBufferRef _Nullable)photoSampleBuffer previewPhotoSampleBuffer:(CMSampleBufferRef _Nullable)previewPhotoSampleBuffer resolvedSettings:(AVCaptureResolvedPhotoSettings * _Nonnull)resolvedSettings bracketSettings:(AVCaptureBracketedStillImageSettings * _Nullable)bracketSettings error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class UIImage;
@class CIFeature;

SWIFT_PROTOCOL("_TtP6Veriff18DeviceCameraAccess_")
@protocol DeviceCameraAccess
- (void)photoCapturedWithImage:(UIImage * _Nullable)image;
- (void)captureDidOutputWithFeatures:(NSArray<CIFeature *> * _Nonnull)features image:(UIImage * _Nonnull)image;
- (void)cameraPermissionGranted;
- (void)noCameraPermission;
- (void)faceDetected;
- (void)noFaceDetected;
@end


SWIFT_PROTOCOL("_TtP6Veriff25LanguageSelectionDelegate_")
@protocol LanguageSelectionDelegate
- (void)didSelectLanguageWithLanguageCode:(NSString * _Nonnull)languageCode;
@end

@class ErrorViewModel;
@class NSCoder;

SWIFT_CLASS("_TtC6Veriff17ErrViewController")
@interface ErrViewController : UIViewController <LanguageSelectionDelegate>
@property (nonatomic, strong) ErrorViewModel * _Null_unspecified errorViewModel;
- (void)viewDidLoad;
- (void)didSelectLanguageWithLanguageCode:(NSString * _Nonnull)languageCode;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ErrorCode, closed) {
  ErrorCodeUNABLE_TO_ACCESS_CAMERA = 0,
  ErrorCodeUNABLE_TO_RECORD_AUDIO = 1,
  ErrorCodeSTATUS_USER_CANCELED = 2,
  ErrorCodeSTATUS_SUBMITTED = 3,
  ErrorCodeSTATUS_OUT_OF_BUSINESS_HOURS = 4,
  ErrorCodeSTATUS_ERROR_SESSION = 5,
  ErrorCodeSTATUS_ERROR_NETWORK = 6,
  ErrorCodeSTATUS_ERROR_NO_IDENTIFICATION_METHODS_AVAILABLE = 7,
  ErrorCodeSTATUS_DONE = 8,
  ErrorCodeSTATUS_VIDEO_CALL_ENDED = 9,
  ErrorCodeSTATUS_ERROR_UNKNOWN = 10,
};

@class VeriffError;

SWIFT_CLASS("_TtC6Veriff14ErrorViewModel")
@interface ErrorViewModel : NSObject
- (nonnull instancetype)initWithError:(VeriffError * _Nonnull)error OBJC_DESIGNATED_INITIALIZER;
- (void)reload;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Veriff10FontLoader")
@interface FontLoader : NSObject
- (void)loadFontsWithFontNames:(NSArray<NSString *> * _Nonnull)fontNames;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC6Veriff12GradientView")
@interface GradientView : UIView
@property (nonatomic, strong) UIColor * _Nonnull firstColor;
@property (nonatomic, strong) UIColor * _Nonnull secondColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP6Veriff19HintOverlayDelegate_")
@protocol HintOverlayDelegate
- (void)hideOverlay;
@end


SWIFT_CLASS("_TtC6Veriff16IBDesignableView")
@interface IBDesignableView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC6Veriff22LanguageViewController")
@interface LanguageViewController : UIViewController <UIGestureRecognizerDelegate>
@property (nonatomic, weak) id <LanguageSelectionDelegate> _Nullable delegate;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPresentationController;

@interface LanguageViewController (SWIFT_EXTENSION(Veriff)) <UIViewControllerTransitioningDelegate>
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nullable)presenting sourceViewController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
@end

@class UITableView;
@class UITableViewCell;

@interface LanguageViewController (SWIFT_EXTENSION(Veriff)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC6Veriff6Locale")
@interface Locale : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;

SWIFT_CLASS("_TtC6Veriff16PhotoHintOverlay")
@interface PhotoHintOverlay : IBDesignableView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified hintTitleLabel;
@property (nonatomic, weak) id <HintOverlayDelegate> _Nullable delegate;
- (void)awakeFromNib;
- (void)updateWithStateWithState:(NSInteger)state;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Veriff13RoundedButton")
@interface RoundedButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class ColorSchema;

@interface UIColor (SWIFT_EXTENSION(Veriff))
+ (UIColor * _Nonnull)veriffBlueColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)defaultGradientStart SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)defaultGradientEnd SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)veriffDarkBlueColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)brightLightBlueColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)veriffYellowColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)selectedButtonColor SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)darkTransparentColor SWIFT_WARN_UNUSED_RESULT;
+ (ColorSchema * _Nullable)customColorSchema SWIFT_WARN_UNUSED_RESULT;
@end




@interface UINavigationController (SWIFT_EXTENSION(Veriff))
- (void)configureAppearance:(UIColor * _Nonnull)color;
- (void)configureClearAppearance;
- (void)configureSemitransparentAppearance;
- (void)configureBlackAppearance;
@end




@interface UIViewController (SWIFT_EXTENSION(Veriff))
@property (nonatomic, weak) id <LanguageSelectionDelegate> _Nullable languageDelegate;
- (void)setupNavBar;
- (void)setupStaticNavbar;
@end


SWIFT_CLASS("_TtC6Veriff11VeriffError")
@interface VeriffError : NSObject
+ (VeriffError * _Nonnull)errorWithCode:(enum ErrorCode)code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Veriff23VeriffNavViewController")
@interface VeriffNavViewController : UINavigationController
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
